package com.wiz.dev.wiztalk.DB;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig xmppMessageDaoConfig;

    private final XmppMessageDao xmppMessageDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        xmppMessageDaoConfig = daoConfigMap.get(XmppMessageDao.class).clone();
        xmppMessageDaoConfig.initIdentityScope(type);

        xmppMessageDao = new XmppMessageDao(xmppMessageDaoConfig, this);

        registerDao(XmppMessage.class, xmppMessageDao);
    }
    
    public void clear() {
        xmppMessageDaoConfig.getIdentityScope().clear();
    }

    public XmppMessageDao getXmppMessageDao() {
        return xmppMessageDao;
    }

}
