package com.wiz.dev.wiztalk.DB;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table XMPP_MESSAGE.
 */
public class XmppMessage {

    private Long id;
    private String sid;
    /**
     * Not-null value.
     */
    private String to_;
    /**
     * Not-null value.
     */
    private String from_;
    private String type;
    private String body;
    private int direct;
    private Long createTime;
    private Integer mold;
    private Integer voiceLength;
    private String filePath;
    private Integer status;
    private Integer readStatus;
    private String extLocalUserName;
    private String extRemoteUserName;
    private String extLocalDisplayName;
    private String extRemoteDisplayName;
    private Integer extGroupOperateType;
    private Integer extGroupOperateIsdeal;
    private String extGroupOperateUserName;
    private String extGroupOperateUserNick;
    private String extGroupMemberUserName;
    private String extGroupMemberUserNick;
    private String extInternalFilePath;
    private String pushToken;
    private String pushContent;
    private Integer pushMsgType;
    private String pushStatusId;
    private String pushtoUserNames;
    private String pushObjectContentBody;
    private String pushObjectContentAppId;
    private String pushObjectContentOperations;
    private Long pushObjectContentPubTime;
    private String pushSessions;
    private Long pushexpire;
    private Integer toReadStatus;
    private Integer recVoiceReadStatus;
    private Long showTime;


    public XmppMessage() {
    }

    public XmppMessage(Long id) {
        this.id = id;
    }

    public XmppMessage(Long id, String sid, String to_, String from_, String type, String body, int direct, Long createTime, Integer mold, Integer voiceLength, String filePath, Integer status, Integer readStatus, String extLocalUserName, String extRemoteUserName, String extLocalDisplayName, String extRemoteDisplayName, Integer extGroupOperateType, Integer extGroupOperateIsdeal, String extGroupOperateUserName, String extGroupOperateUserNick, String extGroupMemberUserName, String extGroupMemberUserNick, String extInternalFilePath, String pushToken, String pushContent, Integer pushMsgType, String pushStatusId, String pushtoUserNames, String pushObjectContentBody, String pushObjectContentAppId, String pushObjectContentOperations, Long pushObjectContentPubTime, String pushSessions, Long pushexpire) {
        this.id = id;
        this.sid = sid;
        this.to_ = to_;
        this.from_ = from_;
        this.type = type;
        this.body = body;
        this.direct = direct;
        this.createTime = createTime;
        this.mold = mold;
        this.voiceLength = voiceLength;
        this.filePath = filePath;
        this.status = status;
        this.readStatus = readStatus;
        this.extLocalUserName = extLocalUserName;
        this.extRemoteUserName = extRemoteUserName;
        this.extLocalDisplayName = extLocalDisplayName;
        this.extRemoteDisplayName = extRemoteDisplayName;
        this.extGroupOperateType = extGroupOperateType;
        this.extGroupOperateIsdeal = extGroupOperateIsdeal;
        this.extGroupOperateUserName = extGroupOperateUserName;
        this.extGroupOperateUserNick = extGroupOperateUserNick;
        this.extGroupMemberUserName = extGroupMemberUserName;
        this.extGroupMemberUserNick = extGroupMemberUserNick;
        this.extInternalFilePath = extInternalFilePath;
        this.pushToken = pushToken;
        this.pushContent = pushContent;
        this.pushMsgType = pushMsgType;
        this.pushStatusId = pushStatusId;
        this.pushtoUserNames = pushtoUserNames;
        this.pushObjectContentBody = pushObjectContentBody;
        this.pushObjectContentAppId = pushObjectContentAppId;
        this.pushObjectContentOperations = pushObjectContentOperations;
        this.pushObjectContentPubTime = pushObjectContentPubTime;
        this.pushSessions = pushSessions;
        this.pushexpire = pushexpire;
    }

    public XmppMessage(Long id, String sid, String to_, String from_, String type, String body, int direct, Long createTime, Integer mold, Integer voiceLength, String filePath, Integer status, Integer readStatus, String extLocalUserName, String extRemoteUserName, String extLocalDisplayName, String extRemoteDisplayName, Integer extGroupOperateType, Integer extGroupOperateIsdeal, String extGroupOperateUserName, String extGroupOperateUserNick, String extGroupMemberUserName, String extGroupMemberUserNick, String extInternalFilePath, String pushToken, String pushContent, Integer pushMsgType, String pushStatusId, String pushtoUserNames, String pushObjectContentBody, String pushObjectContentAppId, String pushObjectContentOperations, Long pushObjectContentPubTime, String pushSessions, Long pushexpire, Integer toReadStatus, Long showTime,Integer recVoiceReadStatus) {
        this.id = id;
        this.sid = sid;
        this.to_ = to_;
        this.from_ = from_;
        this.type = type;
        this.body = body;
        this.direct = direct;
        this.createTime = createTime;
        this.mold = mold;
        this.voiceLength = voiceLength;
        this.filePath = filePath;
        this.status = status;
        this.readStatus = readStatus;
        this.extLocalUserName = extLocalUserName;
        this.extRemoteUserName = extRemoteUserName;
        this.extLocalDisplayName = extLocalDisplayName;
        this.extRemoteDisplayName = extRemoteDisplayName;
        this.extGroupOperateType = extGroupOperateType;
        this.extGroupOperateIsdeal = extGroupOperateIsdeal;
        this.extGroupOperateUserName = extGroupOperateUserName;
        this.extGroupOperateUserNick = extGroupOperateUserNick;
        this.extGroupMemberUserName = extGroupMemberUserName;
        this.extGroupMemberUserNick = extGroupMemberUserNick;
        this.extInternalFilePath = extInternalFilePath;
        this.pushToken = pushToken;
        this.pushContent = pushContent;
        this.pushMsgType = pushMsgType;
        this.pushStatusId = pushStatusId;
        this.pushtoUserNames = pushtoUserNames;
        this.pushObjectContentBody = pushObjectContentBody;
        this.pushObjectContentAppId = pushObjectContentAppId;
        this.pushObjectContentOperations = pushObjectContentOperations;
        this.pushObjectContentPubTime = pushObjectContentPubTime;
        this.pushSessions = pushSessions;
        this.pushexpire = pushexpire;
        this.toReadStatus = toReadStatus;
        this.showTime = showTime;
        this.recVoiceReadStatus = recVoiceReadStatus;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSid() {
        return sid;
    }

    public void setSid(String sid) {
        this.sid = sid;
    }

    /**
     * Not-null value.
     */
    public String getTo_() {
        return to_;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setTo_(String to_) {
        this.to_ = to_;
    }

    /**
     * Not-null value.
     */
    public String getFrom_() {
        return from_;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setFrom_(String from_) {
        this.from_ = from_;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getBody() {
        return body;
    }

    public void setBody(String body) {
        this.body = body;
    }

    public int getDirect() {
        return direct;
    }

    public void setDirect(int direct) {
        this.direct = direct;
    }

    public Long getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    public Integer getMold() {
        return mold;
    }

    public void setMold(Integer mold) {
        this.mold = mold;
    }

    public Integer getVoiceLength() {
        return voiceLength;
    }

    public void setVoiceLength(Integer voiceLength) {
        this.voiceLength = voiceLength;
    }

    public String getFilePath() {
        return filePath;
    }

    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Integer getReadStatus() {
        return readStatus;
    }

    public void setReadStatus(Integer readStatus) {
        this.readStatus = readStatus;
    }

    public String getExtLocalUserName() {
        return extLocalUserName;
    }

    public void setExtLocalUserName(String extLocalUserName) {
        this.extLocalUserName = extLocalUserName;
    }

    public String getExtRemoteUserName() {
        return extRemoteUserName;
    }

    public void setExtRemoteUserName(String extRemoteUserName) {
        this.extRemoteUserName = extRemoteUserName;
    }

    public String getExtLocalDisplayName() {
        return extLocalDisplayName;
    }

    public void setExtLocalDisplayName(String extLocalDisplayName) {
        this.extLocalDisplayName = extLocalDisplayName;
    }

    public String getExtRemoteDisplayName() {
        return extRemoteDisplayName;
    }

    public void setExtRemoteDisplayName(String extRemoteDisplayName) {
        this.extRemoteDisplayName = extRemoteDisplayName;
    }

    public Integer getExtGroupOperateType() {
        return extGroupOperateType;
    }

    public void setExtGroupOperateType(Integer extGroupOperateType) {
        this.extGroupOperateType = extGroupOperateType;
    }

    public Integer getExtGroupOperateIsdeal() {
        return extGroupOperateIsdeal;
    }

    public void setExtGroupOperateIsdeal(Integer extGroupOperateIsdeal) {
        this.extGroupOperateIsdeal = extGroupOperateIsdeal;
    }

    public String getExtGroupOperateUserName() {
        return extGroupOperateUserName;
    }

    public void setExtGroupOperateUserName(String extGroupOperateUserName) {
        this.extGroupOperateUserName = extGroupOperateUserName;
    }

    public String getExtGroupOperateUserNick() {
        return extGroupOperateUserNick;
    }

    public void setExtGroupOperateUserNick(String extGroupOperateUserNick) {
        this.extGroupOperateUserNick = extGroupOperateUserNick;
    }

    public String getExtGroupMemberUserName() {
        return extGroupMemberUserName;
    }

    public void setExtGroupMemberUserName(String extGroupMemberUserName) {
        this.extGroupMemberUserName = extGroupMemberUserName;
    }

    public String getExtGroupMemberUserNick() {
        return extGroupMemberUserNick;
    }

    public void setExtGroupMemberUserNick(String extGroupMemberUserNick) {
        this.extGroupMemberUserNick = extGroupMemberUserNick;
    }

    public String getExtInternalFilePath() {
        return extInternalFilePath;
    }

    public void setExtInternalFilePath(String extInternalFilePath) {
        this.extInternalFilePath = extInternalFilePath;
    }

    public String getPushToken() {
        return pushToken;
    }

    public void setPushToken(String pushToken) {
        this.pushToken = pushToken;
    }

    public String getPushContent() {
        return pushContent;
    }

    public void setPushContent(String pushContent) {
        this.pushContent = pushContent;
    }

    public Integer getPushMsgType() {
        return pushMsgType;
    }

    public void setPushMsgType(Integer pushMsgType) {
        this.pushMsgType = pushMsgType;
    }

    public String getPushStatusId() {
        return pushStatusId;
    }

    public void setPushStatusId(String pushStatusId) {
        this.pushStatusId = pushStatusId;
    }

    public String getPushtoUserNames() {
        return pushtoUserNames;
    }

    public void setPushtoUserNames(String pushtoUserNames) {
        this.pushtoUserNames = pushtoUserNames;
    }

    public String getPushObjectContentBody() {
        return pushObjectContentBody;
    }

    public void setPushObjectContentBody(String pushObjectContentBody) {
        this.pushObjectContentBody = pushObjectContentBody;
    }

    public String getPushObjectContentAppId() {
        return pushObjectContentAppId;
    }

    public void setPushObjectContentAppId(String pushObjectContentAppId) {
        this.pushObjectContentAppId = pushObjectContentAppId;
    }

    public String getPushObjectContentOperations() {
        return pushObjectContentOperations;
    }

    public void setPushObjectContentOperations(String pushObjectContentOperations) {
        this.pushObjectContentOperations = pushObjectContentOperations;
    }

    public Long getPushObjectContentPubTime() {
        return pushObjectContentPubTime;
    }

    public void setPushObjectContentPubTime(Long pushObjectContentPubTime) {
        this.pushObjectContentPubTime = pushObjectContentPubTime;
    }

    public String getPushSessions() {
        return pushSessions;
    }

    public void setPushSessions(String pushSessions) {
        this.pushSessions = pushSessions;
    }

    public Long getPushexpire() {
        return pushexpire;
    }

    public void setPushexpire(Long pushexpire) {
        this.pushexpire = pushexpire;
    }

    public Integer getToReadStatus() {
        return toReadStatus;
    }

    public void setToReadStatus(Integer toReadStatus) {
        this.toReadStatus = toReadStatus;
    }

    public Long getShowTime() {
        return this.showTime;
    }

    public void setShowTime(Long showTime) {
        this.showTime = showTime;
    }

    public Integer getRecVoiceReadStatus(){return recVoiceReadStatus;}

    public void setRecVoiceReadStatus(Integer recVoiceReadStatus){this.recVoiceReadStatus = recVoiceReadStatus;}

    @Override
    public String toString() {
        return "XmppMessage{" +
                "id=" + id +
                ", sid='" + sid + '\'' +
                ", to_='" + to_ + '\'' +
                ", from_='" + from_ + '\'' +
                ", type='" + type + '\'' +
                ", body='" + body + '\'' +
                ", direct=" + direct +
                ", createTime=" + createTime +
                ", mold=" + mold +
                ", voiceLength=" + voiceLength +
                ", filePath='" + filePath + '\'' +
                ", status=" + status +
                ", readStatus=" + readStatus +
                ", extLocalUserName='" + extLocalUserName + '\'' +
                ", extRemoteUserName='" + extRemoteUserName + '\'' +
                ", extLocalDisplayName='" + extLocalDisplayName + '\'' +
                ", extRemoteDisplayName='" + extRemoteDisplayName + '\'' +
                ", extGroupOperateType=" + extGroupOperateType +
                ", extGroupOperateIsdeal=" + extGroupOperateIsdeal +
                ", extGroupOperateUserName='" + extGroupOperateUserName + '\'' +
                ", extGroupOperateUserNick='" + extGroupOperateUserNick + '\'' +
                ", extGroupMemberUserName='" + extGroupMemberUserName + '\'' +
                ", extGroupMemberUserNick='" + extGroupMemberUserNick + '\'' +
                ", extInternalFilePath='" + extInternalFilePath + '\'' +
                ", pushToken='" + pushToken + '\'' +
                ", pushContent='" + pushContent + '\'' +
                ", pushMsgType=" + pushMsgType +
                ", pushStatusId='" + pushStatusId + '\'' +
                ", pushtoUserNames='" + pushtoUserNames + '\'' +
                ", pushObjectContentBody='" + pushObjectContentBody + '\'' +
                ", pushObjectContentAppId='" + pushObjectContentAppId + '\'' +
                ", pushObjectContentOperations='" + pushObjectContentOperations + '\'' +
                ", pushObjectContentPubTime=" + pushObjectContentPubTime +
                ", pushSessions='" + pushSessions + '\'' +
                ", pushexpire=" + pushexpire +
                '}';
    }
}
